{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubelet-check-slack.serviceAccountName" . }}
  namespace: {{ include "kubelet-check-slack.namespace" . }}
  labels:
    {{- include "kubelet-check-slack.labels" . | nindent 4 }}
  {{- with .Values.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubelet-check-slack.clusterRoleName" . }}
  labels:
    {{- include "kubelet-check-slack.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubelet-check-slack.clusterRoleBindingName" . }}
  labels:
    {{- include "kubelet-check-slack.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubelet-check-slack.clusterRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubelet-check-slack.serviceAccountName" . }}
  namespace: {{ include "kubelet-check-slack.namespace" . }}
{{- end }}

