apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubelet-check

resources:
  - namespace.yaml
  - rbac.yaml
  - slack-secret.yaml
  - kubelet-check-job.yaml
  - kubelet-check-cronjob.yaml

